In [1]:
from google.colab import userdata
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
HF_TOKEN = userdata.get('HF_TOKEN')

from huggingface_hub import login
if HF_TOKEN:
    login(token=HF_TOKEN)

In [2]:
import os
!git clone https://oauth2:{GITHUB_TOKEN}@github.com/bencejdanko/bert-tweeteval

# ensure latest
os.chdir('/content/bert-tweeteval')
!cd /content/bert-tweeteval && git pull

Cloning into 'bert-tweeteval'...
remote: Enumerating objects: 66, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 66 (delta 31), reused 49 (delta 16), pack-reused 0 (from 0)
Receiving objects: 100% (66/66), 70.76 KiB | 5.05 MiB/s, done.
Resolving deltas: 100% (31/31), done.
Already up to date.

In [3]:
# copy over package
PACKAGE = "src"

import sys
sys.path.append(f"/content/bert-tweeteval/{PACKAGE}")

In [ ]:
from download import download_and_split_dataset
from train import train_and_evaluate
from analysis import loss_plot

import pandas as pd
from datasets import Dataset

In [5]:
id_labels = {0: "anger", 1: "joy", 2: "optimism", 3: "sadness"}
labels_id = {"anger": 0, "joy": 1, "optimism": 2, "sadness": 3}
candidate_labels = list(id_labels.values())
hypothesis_template = "This tweet expresses {}."

In [6]:
train_df, val_df, test_df = download_and_split_dataset()
print(f"Training set: {len(train_df)}")
print(f"Validation set: {len(val_df)}")
print(f"Testing set: {len(test_df)}")

README.md: 0.00B [00:00, ?B/s]

emotion/train-00000-of-00001.parquet:   0%|          | 0.00/233k [00:00<?, ?B/s]

emotion/test-00000-of-00001.parquet:   0%|          | 0.00/105k [00:00<?, ?B/s]

emotion/validation-00000-of-00001.parque(…):   0%|          | 0.00/28.6k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3257 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1421 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/374 [00:00<?, ? examples/s]

Training set: 3257
Validation set: 374
Testing set: 1421

In [7]:
# create validation split

train_ds = Dataset.from_pandas(train_df)
val_ds = Dataset.from_pandas(val_df)
test_ds = Dataset.from_pandas(test_df)

In [8]:
ft_results = {}

In [ ]:
repo_id = "bdanko/bert-tweeteval"
ft_results["distilbert-base-uncased-tweeteval"] = train_and_evaluate(
    "distilbert-base-uncased",
    train_ds, val_ds, test_ds, test_df,
    "distilbert-base-uncased-tweeteval",
    candidate_labels,
    push_to_hub=True,
    hub_model_id=f"{repo_id}-distilbert"
)

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/3257 [00:00<?, ? examples/s]

Map:   0%|          | 0/374 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...eeteval/training_args.bin: 100%|##########| 5.26kB / 5.26kB

  ...eeteval/model.safetensors:   1%|1         | 3.90MB /  268MB

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating distilbert-base-uncased-tweeteval_StandardTest on provided dataset (size: 1421)...

In [ ]:
loss_plot(ft_results['distilbert-base-uncased-tweeteval']['Log History'], 'DistilBERT')

In [ ]:
repo_id = "bdanko/bert-tweeteval"
ft_results["distilroberta-base-tweeteval"] = train_and_evaluate(
    "distilroberta-base",
    train_ds, val_ds, test_ds, test_df,
    "distilroberta-base-tweeteval",
    candidate_labels,
    push_to_hub=True,
    hub_model_id=f"{repo_id}-distilroberta"
)

config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/331M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/101 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: distilroberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.dense.bias          | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
classifier.out_proj.bias    | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.weight     | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/3257 [00:00<?, ? examples/s]

Map:   0%|          | 0/374 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma'].

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...eeteval/training_args.bin: 100%|##########| 5.26kB / 5.26kB

  ...eeteval/model.safetensors:  12%|#2        | 39.6MB /  328MB

Map:   0%|          | 0/1421 [00:00<?, ? examples/s]

Evaluating distilroberta-base-tweeteval_StandardTest on provided dataset (size: 1421)...

In [ ]:
loss_plot(ft_results['distilroberta-base-tweeteval']['Log History'], 'DistilRoBERTa')

In [11]:
final_df = pd.DataFrame(ft_results).T
print(final_df.to_string(formatters={'Accuracy': '{:,.2%}'.format, 'Macro F1': '{:,.2%}'.format, 'ECE': '{:.4f}'.format, 'Time/100': '{:.2f}s'.format}))

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0                                                        1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             2
distilbert-base-uncased-tweeteval  {'Accuracy': 0.8057705840957072, 'Macro F1': 0.7602419970364312, 'ECE': 0.04759084414966, 'Time/100': 0.08426526329368038, 'Classification Report': '              precision    recall  f1-score   support

       anger       0.83      0.87      0.85       558
         joy       0.82      0.80      0.81       358
    optimism       0.66      0.52      0.58       123
     sadness       0.79      0.80      0.80       382

    accuracy                           0.81      1421
   macro avg       0.78      0.75      0.76      1421
weighted avg       0.80      0.81      0.80      1421
', 'Classification Report Dict': {'anger': {'precision': 0.8299319727891157, 'recall': 0.8745519713261649, 'f1-score': 0.8516579406631762, 'support': 558.0}, 'joy': {'precision': 0.8194842406876791, 'recall': 0.7988826815642458, 'f1-score': 0.809052333804809, 'support': 358.0}, 'optimism': {'precision': 0.6597938144329897, 'recall': 0.5203252032520326, 'f1-score': 0.5818181818181818, 'support': 123.0}, 'sadness': {'precision': 0.7932816537467701, 'recall': 0.8036649214659686, 'f1-score': 0.7984395318595578, 'support': 382.0}, 'accuracy': 0.8057705840957072, 'macro avg': {'precision': 0.7756229204141386, 'recall': 0.749356194402103, 'f1-score': 0.7602419970364312, 'support': 1421.0}, 'weighted avg': {'precision': 0.8027203588240954, 'recall': 0.8057705840957072, 'f1-score': 0.8032606642689384, 'support': 1421.0}}, 'Log History': [{'loss': 1.236930389404297, 'grad_norm': 3.087038040161133, 'learning_rate': 1.975980392156863e-05, 'epoch': 0.24509803921568626, 'step': 50}, {'loss': 0.9091522216796875, 'grad_norm': 7.820976257324219, 'learning_rate': 1.9514705882352942e-05, 'epoch': 0.49019607843137253, 'step': 100}, {'loss': 0.7483244323730469, 'grad_norm': 10.80899715423584, 'learning_rate': 1.9269607843137258e-05, 'epoch': 0.7352941176470589, 'step': 150}, {'loss': 0.6953905487060547, 'grad_norm': 8.930200576782227, 'learning_rate': 1.902450980392157e-05, 'epoch': 0.9803921568627451, 'step': 200}, {'eval_loss': 0.6252315640449524, 'eval_runtime': 0.3404, 'eval_samples_per_second': 1098.792, 'eval_steps_per_second': 70.511, 'epoch': 1.0, 'step': 204}, {'loss': 0.4609444808959961, 'grad_norm': 6.24051570892334, 'learning_rate': 1.8779411764705883e-05, 'epoch': 1.2254901960784315, 'step': 250}, {'loss': 0.485935173034668, 'grad_norm': 5.069647789001465, 'learning_rate': 1.85343137254902e-05, 'epoch': 1.4705882352941178, 'step': 300}, {'loss': 0.5249822235107422, 'grad_norm': 9.532139778137207, 'learning_rate': 1.8289215686274512e-05, 'epoch': 1.715686274509804, 'step': 350}, {'loss': 0.4575718688964844, 'grad_norm': 2.459785223007202, 'learning_rate': 1.8044117647058825e-05, 'epoch': 1.9607843137254903, 'step': 400}, {'eval_loss': 0.6099070310592651, 'eval_runtime': 0.3457, 'eval_samples_per_second': 1081.885, 'eval_steps_per_second': 69.426, 'epoch': 2.0, 'step': 408}, {'loss': 0.3822797393798828, 'grad_norm': 2.7999889850616455, 'learning_rate': 1.7799019607843137e-05, 'epoch': 2.2058823529411766, 'step': 450}, {'loss': 0.2831195640563965, 'grad_norm': 1.1429681777954102, 'learning_rate': 1.7553921568627453e-05, 'epoch': 2.450980392156863, 'step': 500}, {'loss': 0.25106279373168944, 'grad_norm': 11.061517715454102, 'learning_rate': 1.7308823529411766e-05, 'epoch': 2.696078431372549, 'step': 550}, {'loss': 0.2800369453430176, 'grad_norm': 5.6270341873168945, 'learning_rate': 1.706372549019608e-05, 'epoch': 2.9411764705882355, 'step': 600}, {'eval_loss': 0.7301815152168274, 'eval_runtime': 0.3505, 'eval_samples_per_second': 1066.976, 'eval_steps_per_second': 68.469, 'epoch': 3.0, 'step': 612}, {'loss': 0.20874956130981445, 'grad_norm': 17.03197479248047, 'learning_rate': 1.6818627450980395e-05, 'epoch': 3.186274509803922, 'step': 650}, {'loss': 0.19153860092163086, 'grad_norm': 16.380313873291016, 'learning_rate': 1.6573529411764707e-05, 'epoch': 3.431372549019608, 'step': 700}, {'loss': 0.17563539505004883, 'grad_norm': 11.655499458312988, 'learning_rate': 1.632843137254902e-05, 'epoch': 3.6764705882352944, 'step': 750}, {'loss': 0.22447547912597657, 'grad_norm': 0.49841952323913574, 'learning_rate': 1.6083333333333336e-05, 'epoch': 3.9215686274509802, 'step': 800}, {'eval_loss': 0.811371922492981, 'eval_runtime': 0.3509, 'eval_samples_per_second': 1065.777, 'eval_steps_per_second': 68.392, 'epoch': 4.0, 'step': 816}, {'loss': 0.09190680503845215, 'grad_norm': 14.551322937011719, 'learning_rate': 1.583823529411765e-05, 'epoch': 4.166666666666667, 'step': 850}, {'loss': 0.12208590507507325, 'grad_norm': 3.7644126415252686, 'learning_rate': 1.559313725490196e-05, 'epoch': 4.411764705882353, 'step': 900}, {'loss': 0.12165949821472168, 'grad_norm': 29.25946044921875, 'learning_rate': 1.5348039215686277e-05, 'epoch': 4.6568627450980395, 'step': 950}, {'loss': 0.09582024574279785, 'grad_norm': 1.9745620489120483, 'learning_rate': 1.510294117647059e-05, 'epoch': 4.901960784313726, 'step': 1000}, {'eval_loss': 0.9370933175086975, 'eval_runtime': 0.3641, 'eval_samples_per_second': 1027.327, 'eval_steps_per_second': 65.925, 'epoch': 5.0, 'step': 1020}, {'train_runtime': 69.5598, 'train_samples_per_second': 936.46, 'train_steps_per_second': 58.655, 'total_flos': 261112387121040.0, 'train_loss': 0.3924864432390998, 'epoch': 5.0, 'step': 1020}]}  <transformers.trainer.Trainer object at 0x7892a404b7a0>                         BertTokenizer(name_or_path='distilbert-base-uncased', vocab_size=30522, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={\n\t0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),\n\t100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),\n\t101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),\n\t102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),\n\t103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),\n}\n)
distilroberta-base-tweeteval        {'Accuracy': 0.7874736101337086, 'Macro F1': 0.7539477271784956, 'ECE': 0.03163080006565201, 'Time/100': 0.10557901179765329, 'Classification Report': '              precision    recall  f1-score   support

       anger       0.80      0.89      0.84       558
         joy       0.87      0.71      0.78       358
    optimism       0.73      0.57      0.64       123
     sadness       0.73      0.79      0.76       382

    accuracy                           0.79      1421
   macro avg       0.78      0.74      0.75      1421
weighted avg       0.79      0.79      0.79      1421
', 'Classification Report Dict': {'anger': {'precision': 0.8006482982171799, 'recall': 0.8853046594982079, 'f1-score': 0.8408510638297872, 'support': 558.0}, 'joy': {'precision': 0.8668941979522184, 'recall': 0.7094972067039106, 'f1-score': 0.7803379416282642, 'support': 358.0}, 'optimism': {'precision': 0.7291666666666666, 'recall': 0.5691056910569106, 'f1-score': 0.639269406392694, 'support': 123.0}, 'sadness': {'precision': 0.7253012048192771, 'recall': 0.7879581151832461, 'f1-score': 0.7553324968632371, 'support': 382.0}, 'accuracy': 0.7874736101337086, 'macro avg': {'precision': 0.7805025919138355, 'recall': 0.7379664181105688, 'f1-score': 0.7539477271784956, 'support': 1421.0}, 'weighted avg': {'precision': 0.7908954493406365, 'recall': 0.7874736101337086, 'f1-score': 0.7851675070429259, 'support': 1421.0}}, 'Log History': [{'loss': 1.2392059326171876, 'grad_norm': 13.52389144897461, 'learning_rate': 1.975980392156863e-05, 'epoch': 0.24509803921568626, 'step': 50}, {'loss': 0.8746229553222656, 'grad_norm': 16.807167053222656, 'learning_rate': 1.9514705882352942e-05, 'epoch': 0.49019607843137253, 'step': 100}, {'loss': 0.7434838104248047, 'grad_norm': 19.818981170654297, 'learning_rate': 1.9269607843137258e-05, 'epoch': 0.7352941176470589, 'step': 150}, {'loss': 0.7006255340576172, 'grad_norm': 12.855693817138672, 'learning_rate': 1.902450980392157e-05, 'epoch': 0.9803921568627451, 'step': 200}, {'eval_loss': 0.7013135552406311, 'eval_runtime': 0.3875, 'eval_samples_per_second': 965.169, 'eval_steps_per_second': 61.936, 'epoch': 1.0, 'step': 204}, {'loss': 0.5420085525512696, 'grad_norm': 14.35384464263916, 'learning_rate': 1.8779411764705883e-05, 'epoch': 1.2254901960784315, 'step': 250}, {'loss': 0.531202392578125, 'grad_norm': 9.017380714416504, 'learning_rate': 1.85343137254902e-05, 'epoch': 1.4705882352941178, 'step': 300}, {'loss': 0.5480425643920899, 'grad_norm': 19.373435974121094, 'learning_rate': 1.8289215686274512e-05, 'epoch': 1.715686274509804, 'step': 350}, {'loss': 0.5595565795898437, 'grad_norm': 9.685669898986816, 'learning_rate': 1.8044117647058825e-05, 'epoch': 1.9607843137254903, 'step': 400}, {'eval_loss': 0.6442687511444092, 'eval_runtime': 0.3792, 'eval_samples_per_second': 986.417, 'eval_steps_per_second': 63.299, 'epoch': 2.0, 'step': 408}, {'loss': 0.49493629455566407, 'grad_norm': 16.70228385925293, 'learning_rate': 1.7799019607843137e-05, 'epoch': 2.2058823529411766, 'step': 450}, {'loss': 0.38636241912841796, 'grad_norm': 18.086668014526367, 'learning_rate': 1.7553921568627453e-05, 'epoch': 2.450980392156863, 'step': 500}, {'loss': 0.3719316864013672, 'grad_norm': 14.815522193908691, 'learning_rate': 1.7308823529411766e-05, 'epoch': 2.696078431372549, 'step': 550}, {'loss': 0.3890936279296875, 'grad_norm': 23.752151489257812, 'learning_rate': 1.706372549019608e-05, 'epoch': 2.9411764705882355, 'step': 600}, {'eval_loss': 0.6843559145927429, 'eval_runtime': 0.3809, 'eval_samples_per_second': 981.947, 'eval_steps_per_second': 63.013, 'epoch': 3.0, 'step': 612}, {'loss': 0.2953647994995117, 'grad_norm': 17.747711181640625, 'learning_rate': 1.6818627450980395e-05, 'epoch': 3.186274509803922, 'step': 650}, {'loss': 0.27602859497070314, 'grad_norm': 13.38589096069336, 'learning_rate': 1.6573529411764707e-05, 'epoch': 3.431372549019608, 'step': 700}, {'loss': 0.2658000373840332, 'grad_norm': 44.21822738647461, 'learning_rate': 1.632843137254902e-05, 'epoch': 3.6764705882352944, 'step': 750}, {'loss': 0.32808326721191405, 'grad_norm': 21.8695011138916, 'learning_rate': 1.6083333333333336e-05, 'epoch': 3.9215686274509802, 'step': 800}, {'eval_loss': 0.8157830834388733, 'eval_runtime': 0.3834, 'eval_samples_per_second': 975.406, 'eval_steps_per_second': 62.593, 'epoch': 4.0, 'step': 816}, {'loss': 0.23032827377319337, 'grad_norm': 5.127020835876465, 'learning_rate': 1.583823529411765e-05, 'epoch': 4.166666666666667, 'step': 850}, {'loss': 0.22008811950683593, 'grad_norm': 23.081880569458008, 'learning_rate': 1.559313725490196e-05, 'epoch': 4.411764705882353, 'step': 900}, {'loss': 0.1641307258605957, 'grad_norm': 31.262975692749023, 'learning_rate': 1.5348039215686277e-05, 'epoch': 4.6568627450980395, 'step': 950}, {'loss': 0.17665077209472657, 'grad_norm': 47.87700271606445, 'learning_rate': 1.510294117647059e-05, 'epoch': 4.901960784313726, 'step': 1000}, {'eval_loss': 0.9740980267524719, 'eval_runtime': 0.3836, 'eval_samples_per_second': 974.892, 'eval_steps_per_second': 62.56, 'epoch': 5.0, 'step': 1020}, {'train_runtime': 130.3407, 'train_samples_per_second': 499.767, 'train_steps_per_second': 31.303, 'total_flos': 677983271808696.0, 'train_loss': 0.4607759076006272, 'epoch': 5.0, 'step': 1020}]}  <transformers.trainer.Trainer object at 0x7892a3c62090>  RobertaTokenizer(name_or_path='distilroberta-base', vocab_size=50265, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': '<mask>'}, added_tokens_decoder={\n\t0: AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),\n\t1: AddedToken("<pad>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),\n\t2: AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),\n\t3: AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=True, special=True),\n\t50264: AddedToken("<mask>", rstrip=False, lstrip=True, single_word=False, normalized=True, special=True),\n}\n)

In [23]:
final_dict = pd.DataFrame(ft_results["distilbert-base-uncased-tweeteval"][0]["Classification Report Dict"])
final_dict

,anger,joy,optimism,sadness,accuracy,macro avg,weighted avg
precision,0.829932,0.819484,0.659794,0.793282,0.805771,0.775623,0.802720
recall,0.874552,0.798883,0.520325,0.803665,0.805771,0.749356,0.805771
f1-score,0.851658,0.809052,0.581818,0.798440,0.805771,0.760242,0.803261
support,558.000000,358.000000,123.000000,382.000000,0.805771,1421.000000,1421.000000

In [22]:
final_dict = pd.DataFrame(ft_results["distilroberta-base-tweeteval"][0]["Classification Report Dict"])
final_dict

,anger,joy,optimism,sadness,accuracy,macro avg,weighted avg
precision,0.800648,0.866894,0.729167,0.725301,0.787474,0.780503,0.790895
recall,0.885305,0.709497,0.569106,0.787958,0.787474,0.737966,0.787474
f1-score,0.840851,0.780338,0.639269,0.755332,0.787474,0.753948,0.785168
support,558.000000,358.000000,123.000000,382.000000,0.787474,1421.000000,1421.000000