In [1]:
from google.colab import userdata
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')

In [2]:
import os
!git clone https://oauth2:{GITHUB_TOKEN}@github.com/bencejdanko/bert-tweeteval

# ensure latest
os.chdir('/content/bert-tweeteval')
!cd /content/bert-tweeteval && git pull

fatal: destination path 'bert-tweeteval' already exists and is not an empty directory.
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0 (from 0)
Unpacking objects: 100% (4/4), 391 bytes | 391.00 KiB/s, done.
From https://github.com/bencejdanko/bert-tweeteval
   f2a9f7b..ddc692c  main       -> origin/main
Updating f2a9f7b..ddc692c
Fast-forward
 src/zero_shot.py | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)

In [3]:
# copy over package
PACKAGE = "src"

import sys
sys.path.append(f"/content/bert-tweeteval/{PACKAGE}")

In [4]:
from download import download_and_split_dataset
from analysis import print_samples, print_distribution, calculate_ece
from zero_shot import DistilBERT_zero_shot_pipeline, DistilRoBERTa_zero_shot_pipeline, run_benchmarked_inference, run_zero_shot

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/nli-distilroberta-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [5]:
id_labels = {0: "anger", 1: "joy", 2: "optimism", 3: "sadness"}
labels_id = {"anger": 0, "joy": 1, "optimism": 2, "sadness": 3}
candidate_labels = list(id_labels.values())
hypothesis_template = "This tweet expresses {}."

In [6]:
train_df, test_df = download_and_split_dataset()
print(f"Training set: {len(train_df)}")
print(f"Testing set: {len(test_df)}")

Training set: 4041
Testing set: 1011

In [7]:
print_samples(train_df, id_labels)

Label        | Tweet Text
--------------------------------------------------
sadness      | You don't know how to love me when you're sober #sober #selenagomez #revival...
anger        | Dude go out his way to irritate me🙄🙄 that's why I go out my way to not give up a...
sadness      | I saw those dreams dashed &amp;&amp; divided like a million stars in the night s...
sadness      | @user I knew you were going to do that. I would definitely buy if I didn't live ...
sadness      | oh, btw - after a 6 month depression-free time I got a relapse now... superb #de...

In [8]:
print_distribution(train_df, test_df, id_labels)

--- Data Split Summary ---
Training set: 4041
Testing set:  1011

--- Class Distribution (Counts) ---
          Train Count  Test Count  Train %
label
anger            1694         424    41.92
sadness          1061         265    26.26
joy               930         233    23.01
optimism          356          89     8.81

In [9]:
test_df["distilbert_pred"] = run_zero_shot(test_df, DistilBERT_zero_shot_pipeline, candidate_labels , hypothesis_template)

In [10]:
test_df["distilroberta_pred"] = run_zero_shot(test_df, DistilRoBERTa_zero_shot_pipeline, candidate_labels, hypothesis_template)

In [11]:
print(test_df[["text", "label", "distilbert_pred", "distilroberta_pred"]].head())

                                                   text  label  \
4279  I'm still bitter about the fact that I didn't ...      0
3076                ok, ok.. I know.. my last tweet was      1
763   @user @user Oh, hidden revenge and anger...I r...      0
1139  It's not that the man did not know how to jugg...      1
1941  3 hours of hell again. #anxiety. At this point...      0

     distilbert_pred distilroberta_pred
4279         sadness            sadness
3076         sadness            sadness
763            anger              anger
1139         sadness            sadness
1941         sadness              anger

In [12]:
results = {}

In [24]:
results["DistilBERT (WordPiece)"] = run_benchmarked_inference(test_df, DistilBERT_zero_shot_pipeline, candidate_labels, labels_id, hypothesis_template)

In [25]:
results["DistilRoBERTa (BPE)"] = run_benchmarked_inference(test_df, DistilRoBERTa_zero_shot_pipeline, candidate_labels, labels_id, hypothesis_template)

In [26]:
key_metrics = ["Accuracy", "Macro F1", "ECE", "Time/100"]
pd.DataFrame({
    model_name: {metric: results[model_name][metric] for metric in key_metrics}
    for model_name in results.keys()
}).transpose()

                        Accuracy  Macro F1       ECE  Time/100
DistilBERT (WordPiece)  0.529179  0.472531  0.181042  0.294756
DistilRoBERTa (BPE)     0.596439  0.527536  0.056845  0.276464

In [20]:
import pandas as pd
report_df = pd.DataFrame(results["DistilBERT (WordPiece)"]["Classification Report Dict"]).transpose()
report_df

              precision    recall  f1-score      support
anger          0.831933  0.466981  0.598187   424.000000
joy            0.781609  0.291845  0.425000   233.000000
optimism       0.211180  0.382022  0.272000    89.000000
sadness        0.447619  0.886792  0.594937   265.000000
accuracy       0.529179  0.529179  0.529179     0.529179
macro avg      0.568085  0.506910  0.472531  1011.000000
weighted avg   0.664954  0.529179  0.528707  1011.000000

In [18]:
import pandas as pd
report_df = pd.DataFrame(results["DistilRoBERTa (BPE)"]["Classification Report Dict"]).transpose()
report_df

              precision    recall  f1-score      support
anger          0.777778  0.610849  0.684280   424.000000
joy            0.792000  0.424893  0.553073   233.000000
optimism       0.255319  0.269663  0.262295    89.000000
sadness        0.481481  0.833962  0.610497   265.000000
accuracy       0.596439  0.596439  0.596439     0.596439
macro avg      0.576645  0.534842  0.527536  1011.000000
weighted avg   0.657398  0.596439  0.597554  1011.000000