In [1]:
from google.colab import userdata
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')

In [2]:
import os
!git clone https://oauth2:{GITHUB_TOKEN}@github.com/bencejdanko/bert-tweeteval

# ensure latest
os.chdir('/content/bert-tweeteval')
!cd /content/bert-tweeteval && git pull

fatal: destination path 'bert-tweeteval' already exists and is not an empty directory.
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0 (from 0)
Unpacking objects: 100% (4/4), 500 bytes | 500.00 KiB/s, done.
From https://github.com/bencejdanko/bert-tweeteval
   4d18965..004c863  main       -> origin/main
Updating 4d18965..004c863
Fast-forward
 src/train.py | 9 ++++++---
 1 file changed, 6 insertions(+), 3 deletions(-)

In [3]:
# copy over package
PACKAGE = "src"

import sys
sys.path.append(f"/content/bert-tweeteval/{PACKAGE}")

In [4]:
from download import download_and_split_dataset
from train import train_and_evaluate

import pandas as pd
from sklearn.model_selection import train_test_split
from datasets import Dataset

In [5]:
id_labels = {0: "anger", 1: "joy", 2: "optimism", 3: "sadness"}
labels_id = {"anger": 0, "joy": 1, "optimism": 2, "sadness": 3}
candidate_labels = list(id_labels.values())
hypothesis_template = "This tweet expresses {}."

In [6]:
train_df, val_df, test_df = download_and_split_dataset()
print(f"Training set: {len(train_df)}")
print(f"Validation set: {len(val_df)}")
print(f"Testing set: {len(test_df)}")

Training set: 4041
Testing set: 1011

In [7]:
# create validation split

train_ds = Dataset.from_pandas(train_df)
val_ds = Dataset.from_pandas(val_df)
test_ds = Dataset.from_pandas(test_df)

In [8]:
ft_results = {}

In [9]:
ft_results["distilbert-base-uncased-tweeteval"] = train_and_evaluate("distilbert-base-uncased", train_ds, val_ds, test_ds, test_df, "distilbert-base-uncased-tweeteval", candidate_labels)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/3636 [00:00<?, ? examples/s]

Map:   0%|          | 0/405 [00:00<?, ? examples/s]

Map:   0%|          | 0/1011 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.weight', 'distilbert.embeddings.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['distilbert.embeddings.LayerNorm.beta', 'distilbert.embeddings.LayerNorm.gamma'].

Evaluating distilbert-base-uncased-tweeteval on Test Set...

In [11]:
ft_results["distilroberta-base-tweeteval"] = train_and_evaluate("distilroberta-base", train_ds, val_ds, test_ds, test_df, "distilroberta-base-tweeteval", candidate_labels)

config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/331M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/101 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: distilroberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
classifier.dense.weight     | MISSING    |
classifier.out_proj.weight  | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.out_proj.bias    | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/3636 [00:00<?, ? examples/s]

Map:   0%|          | 0/405 [00:00<?, ? examples/s]

Map:   0%|          | 0/1011 [00:00<?, ? examples/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma'].

Evaluating distilroberta-base-tweeteval on Test Set...

In [12]:
final_df = pd.DataFrame(ft_results).T
print(final_df.to_string(formatters={'Accuracy': '{:,.2%}'.format, 'Macro F1': '{:,.2%}'.format, 'ECE': '{:.4f}'.format, 'Time/100': '{:.2f}s'.format}))

                                  Accuracy Macro F1     ECE Time/100                                                                                                                                                                                                                                                                                                                                                                                                                                         Classification Report                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Classification Report Dict
distilbert-base-uncased-tweeteval   80.22%   76.53%  0.0505    0.08s                precision    recall  f1-score   support\n\n       anger       0.82      0.91      0.86       424\n         joy       0.89      0.69      0.78       233\n    optimism       0.58      0.72      0.64        89\n     sadness       0.81      0.76      0.78       265\n\n    accuracy                           0.80      1011\n   macro avg       0.77      0.77      0.77      1011\nweighted avg       0.81      0.80      0.80      1011\n  {'anger': {'precision': 0.8191489361702128, 'recall': 0.9080188679245284, 'f1-score': 0.8612975391498882, 'support': 424.0}, 'joy': {'precision': 0.8895027624309392, 'recall': 0.6909871244635193, 'f1-score': 0.7777777777777778, 'support': 233.0}, 'optimism': {'precision': 0.5765765765765766, 'recall': 0.7191011235955056, 'f1-score': 0.64, 'support': 89.0}, 'sadness': {'precision': 0.8072289156626506, 'recall': 0.7584905660377359, 'f1-score': 0.7821011673151751, 'support': 265.0}, 'accuracy': 0.8021760633036598, 'macro avg': {'precision': 0.7731142977100949, 'recall': 0.7691494205053223, 'f1-score': 0.7652941210607103, 'support': 1011.0}, 'weighted avg': {'precision': 0.8108845406018762, 'recall': 0.8021760633036598, 'f1-score': 0.8018092860141407, 'support': 1011.0}}
distilroberta-base-tweeteval        79.43%   77.26%  0.0792    0.09s                precision    recall  f1-score   support\n\n       anger       0.88      0.80      0.84       424\n         joy       0.80      0.81      0.80       233\n    optimism       0.71      0.67      0.69        89\n     sadness       0.70      0.82      0.76       265\n\n    accuracy                           0.79      1011\n   macro avg       0.77      0.77      0.77      1011\nweighted avg       0.80      0.79      0.80      1011\n     {'anger': {'precision': 0.8805194805194805, 'recall': 0.7995283018867925, 'f1-score': 0.8380716934487021, 'support': 424.0}, 'joy': {'precision': 0.8, 'recall': 0.8068669527896996, 'f1-score': 0.8034188034188035, 'support': 233.0}, 'optimism': {'precision': 0.7142857142857143, 'recall': 0.6741573033707865, 'f1-score': 0.6936416184971098, 'support': 89.0}, 'sadness': {'precision': 0.7035830618892508, 'recall': 0.8150943396226416, 'f1-score': 0.7552447552447552, 'support': 265.0}, 'accuracy': 0.7942631058358062, 'macro avg': {'precision': 0.7745970641736114, 'recall': 0.77391172441748, 'f1-score': 0.7725942176523426, 'support': 1011.0}, 'weighted avg': {'precision': 0.8009507415552322, 'recall': 0.7942631058358062, 'f1-score': 0.7956606759692719, 'support': 1011.0}}

In [15]:
final_dict = pd.DataFrame(ft_results["distilbert-base-uncased-tweeteval"]["Classification Report Dict"])
final_dict

,anger,joy,optimism,sadness,accuracy,macro avg,weighted avg
precision,0.819149,0.889503,0.576577,0.807229,0.802176,0.773114,0.810885
recall,0.908019,0.690987,0.719101,0.758491,0.802176,0.769149,0.802176
f1-score,0.861298,0.777778,0.640000,0.782101,0.802176,0.765294,0.801809
support,424.000000,233.000000,89.000000,265.000000,0.802176,1011.000000,1011.000000

In [14]:
final_dict = pd.DataFrame(ft_results["distilroberta-base-tweeteval"]["Classification Report Dict"])
final_dict

,anger,joy,optimism,sadness,accuracy,macro avg,weighted avg
precision,0.880519,0.800000,0.714286,0.703583,0.794263,0.774597,0.800951
recall,0.799528,0.806867,0.674157,0.815094,0.794263,0.773912,0.794263
f1-score,0.838072,0.803419,0.693642,0.755245,0.794263,0.772594,0.795661
support,424.000000,233.000000,89.000000,265.000000,0.794263,1011.000000,1011.000000